version: "3"
services:
    es-data01:
        image: elasticsearch:7.1.0
        container_name: es-data01
        environment: # setting container env
            - ES_JAVA_OPTS=${ES_JVM_OPTS}   # set es bootstrap jvm args
        restart: always
        volumes:
            - ./es-config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ${DATA_DIR}:/usr/share/elasticsearch/data:rw
            - ${LOGS_DIR}:/usr/share/elasticsearch/logs:rw
        network_mode: "host"
